#!/usr/bin/env python3
"""Generates THIRD-PARTY-NOTICES.md from the real metadata and license files of the bundled dependencies.

Run from anywhere (needs `npm`, `cargo`, the GitHub CLI `gh` and network access for the two UI libraries):
    python3 tools/gen-third-party-notices.py
"""
import hashlib, json, os, subprocess

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
LICENSE_NAMES = ("license", "licence", "copying", "unlicense", "notice")


def license_files(directory):
    out = []
    for f in sorted(os.listdir(directory)):
        if f.lower().startswith(LICENSE_NAMES) and os.path.isfile(os.path.join(directory, f)):
            out.append(os.path.join(directory, f))
    return out


def read(path):
    return open(path, encoding="utf-8", errors="replace").read().strip()


def fetch(url):
    return subprocess.check_output(["curl", "-fsSL", "--max-time", "30", url], text=True).strip()


def fetch_repo_license(repo):
    """License text of a GitHub repository, wherever the file lives (uses the GitHub CLI)."""
    return subprocess.check_output(["gh", "api", f"repos/{repo}/license", "-q", ".content"], text=True).strip() and \
        subprocess.check_output("gh api repos/%s/license -q .content | base64 -d" % repo, shell=True, text=True).strip()


def repo_license(repo_url):
    """Fallback for packages that ship no license file: the license of their GitHub repository."""
    import re
    m = re.match(r"https?://github\.com/([^/]+/[^/#]+?)(?:\.git)?/?$", repo_url or "")
    if not m:
        return []
    try:
        return [fetch_repo_license(m.group(1))]
    except Exception:
        return []


def section_js():
    """Packages bundled into bin/plugin.js (production dependencies of the plugin)."""
    out = subprocess.check_output(["npm", "ls", "--omit=dev", "--all", "--parseable"], cwd=os.path.join(ROOT, "plugin"), text=True)
    rows = []
    for d in out.strip().split("\n")[1:]:
        j = json.load(open(os.path.join(d, "package.json")))
        texts = [read(f) for f in license_files(d)]
        rows.append((j["name"], j["version"], j.get("license", "?"), (j.get("repository") or {}).get("url", "") if isinstance(j.get("repository"), dict) else j.get("repository", ""), texts))
    return sorted(rows)


def section_rust():
    meta = json.loads(subprocess.check_output(["cargo", "metadata", "--format-version", "1"], cwd=os.path.join(ROOT, "engine-rs"), text=True))
    rows = []
    for p in meta["packages"]:
        if p["name"] == "saap-engine":
            continue
        texts = [read(f) for f in license_files(os.path.dirname(p["manifest_path"]))]
        repo = p.get("repository") or "https://crates.io/crates/" + p["name"]
        if not texts:
            texts = repo_license(repo)
        rows.append((p["name"], p["version"], p["license"] or "?", repo, texts))
    return sorted(rows)


def render_texts(rows):
    """Full license texts, each distinct text printed once with the packages it applies to."""
    groups = {}
    for name, version, _lic, _repo, texts in rows:
        for t in texts:
            groups.setdefault(hashlib.sha256(t.encode()).hexdigest(), (t, []))[1].append(f"{name} {version}")
    out = []
    for t, pkgs in sorted(groups.values(), key=lambda g: g[1][0]):
        out.append(f"#### Applies to: {', '.join(pkgs)}\n\n```text\n{t}\n```\n")
    return "\n".join(out)


def table(rows):
    lines = ["| Package | Version | License | Source |", "|---|---|---|---|"]
    for name, version, lic, repo, _ in rows:
        lines.append(f"| {name} | {version} | {lic} | {repo} |")
    return "\n".join(lines)


js, rust = section_js(), section_rust()
for name, version, lic, _repo, texts in js + rust:
    if not texts:
        print(f"warning: no license file found for {name} {version} ({lic}) — listed in the table only")
sdpi = fetch_repo_license("GeekyEggo/sdpi-components")
lit = fetch_repo_license("lit/lit")

doc = f"""# Third-party notices

SAAP Audio itself is released under the [MIT License](LICENSE). It includes or is built with the third-party
software listed below, each under its own license. This file is generated by `tools/gen-third-party-notices.py`.

The Windows engine list below is the full dependency graph of `engine-rs/Cargo.lock`. It includes crates that only apply
to other platforms (Android, UEFI…) and are not part of the macOS or Windows builds; a few of them ship no license
file and are listed in the table only.

Dual-licensed packages (for example "MIT OR Apache-2.0") are used under the MIT or Apache-2.0 terms.
The `symphonia` crates are under the MPL-2.0: their unmodified source code is available from the links below and from
[github.com/pdeljanov/Symphonia](https://github.com/pdeljanov/Symphonia).

## Settings panels (bundled as `ui/sdpi-components.js`)

**sdpi-components** v4 — MIT — https://sdpi-components.dev

```text
{sdpi}
```

**Lit** (bundled inside sdpi-components) — BSD-3-Clause — https://lit.dev

```text
{lit}
```

## Plugin (bundled into `bin/plugin.js`)

{table(js)}

### License texts

{render_texts(js)}

## Windows audio engine (`saap-engine.exe`, compiled from `engine-rs/`)

{table(rust)}

### License texts

{render_texts(rust)}
"""
open(os.path.join(ROOT, "THIRD-PARTY-NOTICES.md"), "w", encoding="utf-8").write(doc)
print(f"OK: {len(js)} JS packages, {len(rust)} Rust crates, {len(doc) // 1024} KB")
